//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use crate::dao::castle::CastleSide;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "castle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub clan_id: i32,
    pub side: CastleSide,
    pub treasury: i64,
    pub siege_starts_at: Option<DateTimeWithTimeZone>,
    pub registration_ends_at: Option<DateTimeWithTimeZone>,
    pub show_npc_crest: bool,
    pub ticket_buy_count: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clan_ally::Entity",
        from = "Column::ClanId",
        to = "super::clan_ally::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClanAlly,
}

impl Related<super::clan_ally::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClanAlly.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
