//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod castle;
pub mod character;
pub mod character_mail;
pub mod clan_ally;
pub mod crest;
pub mod item;
pub mod quest;
pub mod skill;
pub mod user;
