//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::castle::Entity as Castle;
pub use super::character::Entity as Character;
pub use super::character_mail::Entity as CharacterMail;
pub use super::clan_ally::Entity as ClanAlly;
pub use super::crest::Entity as Crest;
pub use super::item::Entity as Item;
pub use super::skill::Entity as Skill;
pub use super::user::Entity as User;
