[package]
name = "migration"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std.workspace = true
sea-orm.workspace = true

[dependencies.sea-orm-migration]
workspace = true
