$schema: "http://json-schema.org/draft-07/schema#"
title: "Action list Schema"
type: "object"
required:
  - actions
properties:
  actions:
    type: "array"
    items:
      properties:
        id:
          type: integer
          minimum: 0
        handler:
          type: string
        option:
          type: string
