$schema: "http://json-schema.org/draft-07/schema#"
title: "Stat bonus Schema"
type: "object"
required:
  - STR
  - CON
  - DEX
  - INT
  - WIT
  - MEN
properties:
  STR: &arrayItem
    type: array
    minItems: 1
    maxItems: 201
    items:
      type: object
      properties:
        bonus:
          type: number
        value:
          type: integer
  INT: *arrayItem
  CON: *arrayItem
  MEN: *arrayItem
  DEX: *arrayItem
  WIT: *arrayItem