use crate::game_objects::creature::Creature;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Stat {
    //HP/MP/CP
    HpLimit,
    MaxHp,
    MaxMp,
    MaxCp,
    MaxRecoverableHp,
    MaxRecoverableMp,
    MaxRecoverableCp,
    RegenerateHpRate,
    RegenerateCpRate,
    RegenerateMpRate,
    AdditionalPotionHp,
    AdditionalPotionMp,
    AdditionalPotionCp,
    ManaCharge,
    HealEffect,
    HealEffectAdd,
    //Attack and Defence
    PhysicalDefence,
    MagicalDefence,
    PhysicalAttack,
    MagicAttack,
    PhysicalAttackSpeed,
    MagicAttackSpeed,
    AtkReuse,
    ShieldDefence,
    CriticalDamage,
    CriticalDamageAdd,
    HateAttack,
    RearDamageRate,
    DragonWeaponDefence,
    AutoAttackDamageBonus,
    // Pvp bonus
    PvpPhysicalAttackDamage,
    PvpMagicalSkillDamage,
    PvpPhysicalSkillDamage,
    PvpPhysicalAttackDefence,
    PvpMagicalSkillDefence,
    PvpPhysicalSkillDefence,
    //Pve bonus
    PvePhysicalAttackDamage,
    PvePhysicalSkillDamage,
    PveMagicalSkillDamage,
    PvePhysicalAttackDefence,
    PvePhysicalSkillDefence,
    PveMagicalSkillDefence,
    PveRaidPhysicalAttackDamage,
    PveRaidPhysicalSkillDamage,
    PveRaidMagicalSkillDamage,
    PveRaidPhysicalAttackDefence,
    PveRaidPhysicalSkillDefence,
    PveRaidMagicalSkillDefence,
    //fixed damage
    PvpDamageTaken,
    PveDamageTaken,
    //Attack and defence rates
    MagicCriticalDamage,
    SkillPowerAdd,
    PhysicalSkillPower,
    MagicalSkillPower,
    PhysicalSkillCriticalDamage,
    PhysicalSkillCriticalDamageAdd,
    MagicCriticalDamageAdd,
    ShieldDefenceRate,
    CriticalRate,
    CriticalRateSkill,
    AddMaxMagicCriticalRate,
    AddMaxPhysicalCriticalRate,
    MagicCriticalRate,
    BlowRate,
    BlowRateDefence,
    DefenceCriticalRate,
    DefenceCriticalRateAdd,
    DefenceMagicCriticalRate,
    DefenceMagicCriticalRateAdd,
    DefenceCriticalDamage,
    DefenceMagicCriticalDamage,
    DefenceMagicCriticalDamageAdd,
    DefenceCriticalDamageAdd,
    DefencePhysicalSkillCriticalDamage,
    DefencePhysicalSkillCriticalDamageAdd,
    InstantKillResist,
    ExpspRate,
    BonusExp,
    BonusSp,
    BonusDropAdena,
    BonusDropAmount,
    BonusDropRate,
    BonusSpoilRate,
    AttackCancel,
    //Accuracy and range
    AccuracyCombat,
    AccuracyMagic,
    EvasionRate,
    MagicEvasionRate,
    PhysicalAttackRange,
    MagicAttackRange,
    AttackCountMax,
    PhysicalPolearmTargetSingle,
    // Run speed, walk & escape speed are calculated proportionally, magic speed is a buff
    MoveSpeed,
    SpeedLimit,
    RunSpeed,
    WalkSpeed,
    SwimRunSpeed,
    SwimWalkSpeed,
    FlyRunSpeed,
    FlyWalkSpeed,
    //Basic stats
    Str,
    Con,
    Dex,
    Int,
    Wit,
    Men,
    // Special stats, share one slot in Calculator
    Breath,
    Fall,
    FishingExpSpBonus,
    EnchantRate,
    //Vulnerabilities
    DamageZoneVuln,
    ResistDispelBuff,
    ResistAbnormalDebuff,
    //RESIST
    FireRes,
    WindRes,
    WaterRes,
    EarthRes,
    HolyRes,
    DarkRes,
    BaseAttributeRes,
    MagicSuccessRes,
    //buff immunity
    AbnormalResistPhysical,
    AbnormalResistMagical,
    RealDamageResist,
    //element power
    FirePower,
    WaterPower,
    WindPower,
    EarthPower,
    HolyPower,
    DarkPower,
    //PROFICIENCY
    ReflectDamagePercent,
    ReflectDamagePercentDefense,
    ReflectSkillMagic,
    ReflectSkillPhysic,
    VengeanceSkillMagicDamage,
    VengeanceSkillPhysicalDamage,
    AbsorbDamagePercent,
    AbsorbDamageChance,
    AbsorbDamageDefence,
    TransferDamageSummonPercent,
    ManaShieldPercent,
    TransferDamageToPlayer,
    AbsorbManaDamagePercent,
    AbsorbManaDamageChance,
    //WEIGHT
    WeightLimit,
    WeightPenalty,
    //ExSkill
    InventoryNormal,
    StoragePrivate,
    TradeSell,
    TradeBuy,
    RecipeDwarven,
    RecipeCommon,
    //skill mastery
    SkillMastery,
    SkillMasteryRate,
    //Vitality
    VitalityConsumeRate,
    VitalityExpRate,

    ReduceExpLostByPvp,
    ReduceExpLostByMob,
    ReduceExpLostByRaid,

    ReduceDeathPenaltyByPvp,
    ReduceDeathPenaltyByMob,
    ReduceDeathPenaltyByRaid,
    MaxSummonPoints,
    MaxCubic,
    // The maximum allowed range to be damaged/debuffed from.
    SphericBarrierRange,
    // Blocks given amount of debuffs.
    DebuffBlock,
    // Affects the random weapon damage.
    RandomDamage,
    // Affects the random weapon damage.
    DamageLimit,
    // Maximun momentum one can charge
    MaxMomentum,

    // Which base stat ordinal should alter skill critical formula.
    BonusSkillCritical,
    BonusSpeed,
    CraftingCritical,
    ShotsBonus,
    WorldChatPoints,
    AttackDamage,
    ImmobileDamageBonus,
    ImmobileDamageResist,
    CraftRate,
}

impl Stat {
    #[allow(clippy::too_many_lines)]
    pub fn calc(self, _creature: &dyn Creature, _base: Option<f64>) -> f64 {
        #[allow(clippy::enum_glob_use)]
        use Stat::*;
        match self {
            HpLimit => 0.0,
            MaxHp => -1.0,
            MaxMp => -1.0,
            MaxCp => -1.0,
            MaxRecoverableHp => -1.0,
            MaxRecoverableMp => -1.0,
            MaxRecoverableCp => -1.0,
            RegenerateHpRate => -1.0,
            RegenerateCpRate => -1.0,
            RegenerateMpRate => -1.0,
            AdditionalPotionHp => -1.0,
            AdditionalPotionMp => -1.0,
            AdditionalPotionCp => -1.0,
            ManaCharge => -1.0,
            HealEffect => -1.0,
            HealEffectAdd => -1.0,
            PhysicalDefence => -1.0,
            MagicalDefence => -1.0,
            PhysicalAttack => -1.0,
            MagicAttack => -1.0,
            PhysicalAttackSpeed => -1.0,
            MagicAttackSpeed => -1.0,
            AtkReuse => -1.0,
            ShieldDefence => -1.0,
            CriticalDamage => -1.0,
            CriticalDamageAdd => -1.0,
            HateAttack => -1.0,
            RearDamageRate => -1.0,
            DragonWeaponDefence => -1.0,
            AutoAttackDamageBonus => -1.0,
            PvpPhysicalAttackDamage => -1.0,
            PvpMagicalSkillDamage => -1.0,
            PvpPhysicalSkillDamage => -1.0,
            PvpPhysicalAttackDefence => -1.0,
            PvpMagicalSkillDefence => -1.0,
            PvpPhysicalSkillDefence => -1.0,
            PvePhysicalAttackDamage => -1.0,
            PvePhysicalSkillDamage => -1.0,
            PveMagicalSkillDamage => -1.0,
            PvePhysicalAttackDefence => -1.0,
            PvePhysicalSkillDefence => -1.0,
            PveMagicalSkillDefence => -1.0,
            PveRaidPhysicalAttackDamage => -1.0,
            PveRaidPhysicalSkillDamage => -1.0,
            PveRaidMagicalSkillDamage => -1.0,
            PveRaidPhysicalAttackDefence => -1.0,
            PveRaidPhysicalSkillDefence => -1.0,
            PveRaidMagicalSkillDefence => -1.0,
            PvpDamageTaken => -1.0,
            PveDamageTaken => -1.0,
            MagicCriticalDamage => -1.0,
            SkillPowerAdd => -1.0,
            PhysicalSkillPower => -1.0,
            MagicalSkillPower => -1.0,
            PhysicalSkillCriticalDamage => -1.0,
            PhysicalSkillCriticalDamageAdd => -1.0,
            MagicCriticalDamageAdd => -1.0,
            ShieldDefenceRate => -1.0,
            CriticalRate => -1.0,
            CriticalRateSkill => -1.0,
            AddMaxMagicCriticalRate => -1.0,
            AddMaxPhysicalCriticalRate => -1.0,
            MagicCriticalRate => -1.0,
            BlowRate => -1.0,
            BlowRateDefence => -1.0,
            DefenceCriticalRate => -1.0,
            DefenceCriticalRateAdd => -1.0,
            DefenceMagicCriticalRate => -1.0,
            DefenceMagicCriticalRateAdd => -1.0,
            DefenceCriticalDamage => -1.0,
            DefenceMagicCriticalDamage => -1.0,
            DefenceMagicCriticalDamageAdd => -1.0,
            DefenceCriticalDamageAdd => -1.0,
            DefencePhysicalSkillCriticalDamage => -1.0,
            DefencePhysicalSkillCriticalDamageAdd => -1.0,
            InstantKillResist => -1.0,
            ExpspRate => -1.0,
            BonusExp => -1.0,
            BonusSp => -1.0,
            BonusDropAdena => -1.0,
            BonusDropAmount => -1.0,
            BonusDropRate => -1.0,
            BonusSpoilRate => -1.0,
            AttackCancel => -1.0,
            AccuracyCombat => -1.0,
            AccuracyMagic => -1.0,
            EvasionRate => -1.0,
            MagicEvasionRate => -1.0,
            PhysicalAttackRange => -1.0,
            MagicAttackRange => -1.0,
            AttackCountMax => -1.0,
            PhysicalPolearmTargetSingle => -1.0,
            MoveSpeed => -1.0,
            SpeedLimit => -1.0,
            RunSpeed => -1.0,
            WalkSpeed => -1.0,
            SwimRunSpeed => -1.0,
            SwimWalkSpeed => -1.0,
            FlyRunSpeed => -1.0,
            FlyWalkSpeed => -1.0,
            Str => -1.0,
            Con => -1.0,
            Dex => -1.0,
            Int => -1.0,
            Wit => -1.0,
            Men => -1.0,
            Breath => -1.0,
            Fall => -1.0,
            FishingExpSpBonus => -1.0,
            EnchantRate => -1.0,
            DamageZoneVuln => -1.0,
            ResistDispelBuff => -1.0,
            ResistAbnormalDebuff => -1.0,
            FireRes => -1.0,
            WindRes => -1.0,
            WaterRes => -1.0,
            EarthRes => -1.0,
            HolyRes => -1.0,
            DarkRes => -1.0,
            BaseAttributeRes => -1.0,
            MagicSuccessRes => -1.0,
            AbnormalResistPhysical => -1.0,
            AbnormalResistMagical => -1.0,
            RealDamageResist => -1.0,
            FirePower => -1.0,
            WaterPower => -1.0,
            WindPower => -1.0,
            EarthPower => -1.0,
            HolyPower => -1.0,
            DarkPower => -1.0,
            ReflectDamagePercent => -1.0,
            ReflectDamagePercentDefense => -1.0,
            ReflectSkillMagic => -1.0,
            ReflectSkillPhysic => -1.0,
            VengeanceSkillMagicDamage => -1.0,
            VengeanceSkillPhysicalDamage => -1.0,
            AbsorbDamagePercent => -1.0,
            AbsorbDamageChance => -1.0,
            AbsorbDamageDefence => -1.0,
            TransferDamageSummonPercent => -1.0,
            ManaShieldPercent => -1.0,
            TransferDamageToPlayer => -1.0,
            AbsorbManaDamagePercent => -1.0,
            AbsorbManaDamageChance => -1.0,
            WeightLimit => -1.0,
            WeightPenalty => -1.0,
            InventoryNormal => -1.0,
            StoragePrivate => -1.0,
            TradeSell => -1.0,
            TradeBuy => -1.0,
            RecipeDwarven => -1.0,
            RecipeCommon => -1.0,
            SkillMastery => -1.0,
            SkillMasteryRate => -1.0,
            VitalityConsumeRate => -1.0,
            VitalityExpRate => -1.0,
            ReduceExpLostByPvp => -1.0,
            ReduceExpLostByMob => -1.0,
            ReduceExpLostByRaid => -1.0,
            ReduceDeathPenaltyByPvp => -1.0,
            ReduceDeathPenaltyByMob => -1.0,
            ReduceDeathPenaltyByRaid => -1.0,
            MaxSummonPoints => -1.0,
            MaxCubic => -1.0,
            SphericBarrierRange => -1.0,
            DebuffBlock => -1.0,
            RandomDamage => -1.0,
            DamageLimit => -1.0,
            MaxMomentum => -1.0,
            BonusSkillCritical => -1.0,
            BonusSpeed => -1.0,
            CraftingCritical => -1.0,
            ShotsBonus => -1.0,
            WorldChatPoints => -1.0,
            AttackDamage => -1.0,
            ImmobileDamageBonus => -1.0,
            ImmobileDamageResist => -1.0,
            CraftRate => -1.0,
        }
    }
}
